"""Add Financial Integrity and Activity Logs

Revision ID: 131d8685d2ab
Revises: 5cb8ff74d171
Create Date: 2026-05-11 22:04:46.771725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131d8685d2ab'
down_revision: Union[str, Sequence[str], None] = '5cb8ff74d171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('is_reversible', sa.Boolean(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_closings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.Column('opening_cash', sa.Float(), nullable=True),
    sa.Column('actual_cash', sa.Float(), nullable=True),
    sa.Column('system_cash', sa.Float(), nullable=True),
    sa.Column('system_card', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_closings_closing_date'), 'daily_closings', ['closing_date'], unique=False)
    op.add_column('inventory_items', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('cash_amount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('card_amount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('is_voided', sa.Boolean(), nullable=True))
    op.add_column('sales', sa.Column('void_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'void_reason')
    op.drop_column('sales', 'is_voided')
    op.drop_column('sales', 'card_amount')
    op.drop_column('sales', 'cash_amount')
    op.drop_column('inventory_items', 'low_stock_threshold')
    op.drop_index(op.f('ix_daily_closings_closing_date'), table_name='daily_closings')
    op.drop_table('daily_closings')
    op.drop_table('activity_logs')
    op.drop_table('notifications')
    # ### end Alembic commands ###
