"""fix missing columns and tables batch

Revision ID: e9053aafee3c
Revises: 20260511_0001
Create Date: 2026-05-12 23:15:48.794665
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9053aafee3c'
down_revision = '20260511_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_inventory_items_sku', ['sku'])

    with op.batch_alter_table('repair_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('accessories', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('warranty_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('advance_payment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_completion', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('serial_number',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('card_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_voided', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('void_reason', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('void_reason')
        batch_op.drop_column('is_voided')
        batch_op.drop_column('card_amount')
        batch_op.drop_column('cash_amount')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('serial_number',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('repair_tickets', schema=None) as batch_op:
        batch_op.drop_column('estimated_completion')
        batch_op.drop_column('advance_payment')
        batch_op.drop_column('warranty_status')
        batch_op.drop_column('priority')
        batch_op.drop_column('accessories')
        batch_op.drop_column('condition_notes')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
